### ISSUE TITLE
where is the code?

### ISSUE THREAD

**Issue by iFighting** [NVlabs/wetectron#5]
where is the code?

**Comment by jason718** [comment]
We want to thank for the attention of this work. We are sorry for the delay and are actively working for a high-quality code base. The purpose of this repo was to create a placeholder so that everyone knows where the code will appear in the first place. The delay is mostly due to:
- The original code was built on "Mask R-CNN Benchmark". We are working to switch to Detectron2 so that it is compatible with the latest supervised research.
- IP, legal approval and code review can take time.
- We have an upcoming ECCV paper highly related to the CVPR work. We plan to release a unified codebase that covers both.

Apologize again. Feel free to raise any technical questions here or email the authors. We are more than happy to answer.

**Comment by bkonk** [comment]
Do you have an estimate for when the code will be available?

**Comment by LoveIsAGame** [comment]
Do you have an estimate for when the code will be available?

**Comment by jason718** [comment]
In ~2-3 weeks if everything goes smooth.
