### ISSUE TITLE
One Question With Nothing About This Article

### ISSUE THREAD

**Issue by hhhh12345678** [NVlabs/wetectron#56]
Thanks for your great job~

I have a question that with nothing about this article. I am sorry about put this on issues, but I do not get suitable one to discuss with. Hope you can understand and give your advices.

Q: Based on your codes, I got 53.1mAP on VOC2007. Then I used the WSOD results to trian the fully supervised object detector (FSOD) with Faster-RCNN and FPN. But I got a very low performance on VOC2007(41.3mAP) whice is very confusing. From the articles I read before (such as OICR, WSDDN, PCL), althought based on Faster-RCNN instead of Fast-rcnn, training a FSOD based on WSOD results can always gets a better mAP than using single WSOD. Is this caused by the different of Faster-RCNN and Fast-RCNN? Based on your experience, do you have any other suggestions for this situation？

**Comment by jason718** [comment]
I don't think faster RCNN and fast RCNN make a big difference. However, it could be true since faster-rcnn might learn very bad proposals (RPN). In fast rcnn, you can just use selective search.

When you generate the pseudo-labels, you can decide how to do it. Existing methods take top-1 if I recall correctly. you can always add more heuristics.
